CREATE SCHEMA SpecifikacijeSoftverskihSistemaProjekat;
use SpecifikacijeSoftverskihSistemaProjekat;


CREATE TABLE ClientTable (
id  BIGINT AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
surname VARCHAR(20) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(50) NOT NULL,
phoneNumber VARCHAR(12) UNIQUE NOT NULL,
address VARCHAR(50) NOT NULL,
cardNumber VARCHAR(20) UNIQUE NOT NULL,
nativeLanguage ENUM('SERBIAN','ENGLISH','GERMAN','ITALIAN','FRENCH','RUSSIAN') NOT NULL,
role ENUM('ADMIN','CLIENT','TRAINER'),
height INT NOT NULL,
weight INT NOT NULL,
illnessOrCondition VARCHAR(40),
waistCircumference DOUBLE NOT NULL,
stomachCircumference DOUBLE NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE Trainer (
id BIGINT AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
surname VARCHAR(20) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(50) NOT NULL,
phoneNumber VARCHAR(12) UNIQUE NOT NULL,
address VARCHAR(50) NOT NULL,
cardNumber VARCHAR(20) UNIQUE NOT NULL,
nativeLanguage ENUM('SERBIAN','ENGLISH','GERMAN','ITALIAN','FRENCH','RUSSIAN') NOT NULL,
role ENUM('ADMIN','CLIENT','TRAINER'),
certificate VARCHAR(50),
diploma VARCHAR(50),
title VARCHAR(50),
isActive BOOLEAN DEFAULT FALSE ,
salary DOUBLE DEFAULT 0,
PRIMARY KEY(id)
);

CREATE TABLE Admin (
id BIGINT AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
surname VARCHAR(20) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(50) NOT NULL,
phoneNumber VARCHAR(12) UNIQUE NOT NULL,
address VARCHAR(50) NOT NULL,
cardNumber VARCHAR(20) UNIQUE NOT NULL,
nativeLanguage ENUM('SERBIAN','ENGLISH','GERMAN','ITALIAN','FRENCH','RUSSIAN') NOT NULL,
role ENUM('ADMIN','CLIENT','TRAINER'),
PRIMARY KEY(id)
);
CREATE TABLE Appointment(
id  BIGINT AUTO_INCREMENT,
idTrainer BIGINT NOT NULL,
idClient BIGINT NOT NULL,
isFree BOOLEAN DEFAULT TRUE NOT NULL,
dateAndTime DATETIME NOT NULL,
price DOUBLE NOT NULL,
rating ENUM('1','2','3','4','5') NOT NULL,
comment VARCHAR(35) NOT NULL,
FOREIGN KEY (idTrainer) REFERENCES Trainer(id) ON DELETE CASCADE,
FOREIGN KEY (idClient) REFERENCES ClientTable(id) ON DELETE CASCADE,
primary key(id)
);

CREATE TABLE clientSpeaks(
clientId BIGINT NOT NULL,
speaksLangague ENUM('SERBIAN','ENGLISH','GERMAN','ITALIAN','FRENCH','RUSSIAN') NOT NULL,
FOREIGN KEY (clientId) REFERENCES ClientTable(id) ON DELETE CASCADE
);

CREATE TABLE trainerSpeaks(
trainerId BIGINT NOT NULL,
speaksLangague ENUM('SERBIAN','ENGLISH','GERMAN','ITALIAN','FRENCH','RUSSIAN') NOT NULL,
FOREIGN KEY (trainerId) REFERENCES Trainer(id) ON DELETE CASCADE
);

CREATE TABLE adminSpeaks(
adminId BIGINT NOT NULL,
speaksLangague ENUM('SERBIAN','ENGLISH','GERMAN','ITALIAN','FRENCH','RUSSIAN') NOT NULL,
FOREIGN KEY (adminId) REFERENCES Admin(id) ON DELETE CASCADE
);

CREATE TABLE clientProps (
clientId BIGINT NOT NULL,
prop ENUM('MAT','JUMP_ROPE','DUMBBELLS','BAND','BARBELL','ABBROLLER','TREADMILL','BIKE') NOT NULL,
FOREIGN KEY (clientId) REFERENCES ClientTable(id) ON DELETE CASCADE
);

CREATE TABLE clientGoals (
clientId BIGINT NOT NULL,
goal ENUM('GAIN_WEIGHT','LOSE_WEIGHT','ENDURANCE','STRENGTH','FLEXIBILITY','RECOVERY') NOT NULL,
FOREIGN KEY (clientId) REFERENCES ClientTable(id) ON DELETE CASCADE
);


INSERT INTO Trainer VALUES(1, 'Milan','Milanic','milanmilanic@gmail.com', 'password', '060 3311 964','address','160-216125-49','SERBIAN','TRAINER','DIPLOMIRANI PROFESOR FIZICKOG VASPITANJA','PROFESOR SPORTA I FIZICKOG VASPITANJA', 'Title',FALSE,40000);

insert into Admin values(1,'Test','Testovic','testovic@gmail.com','test','212321312','adresa','160-216125-09','SERBIAN','ADMIN');
